### ISSUE TITLE
Morning session code review.

### ISSUE THREAD

**Issue by Fadahunsiseyi** [OyePriscilla/First-Microverse-Capstone-Project#4]
- I had an amazing time reviewing your code 👏
- Github deployment well done, right usage of the semantics 👍.
- It would be nice to change the text color of the contact section in your about page.
- It would be nice to have the home page displayed in the about page. When in the about page, it would be nice if the about page isn't showing.
- It would be nice to get to the home page by clicking on the logo in the about page.

**Comment by OyePriscilla** [comment]
Thanks for the review.
